version: 0.2
env:
  variables:
    APP_VERSION: 0.1.0
phases:
  build:
    commands:
      - set -o errexit; set -o nounset; set -o xtrace; 
      - find . -name '*.sh' -type f -exec chmod 0755 '{}' ';'
      - ./build.sh
