apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bridgess
  namespace: tableau
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bridgess
    kind: SecretStore
  target:
    name: bridgesecret
    creationPolicy: Owner
  data:
  - secretKey: pat
    remoteRef:
      key: SiteOneSecret #AWS Secrets Manager secret name