apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: bridgess
  namespace: tableau
spec:
  provider:
    aws:
      service: SecretsManager
      region: $REGION
      auth:
        jwt:
          serviceAccountRef:
            name: bridgesa