apiVersion: batch/v1
kind: CronJob
metadata:
  name: pat-client
  labels:
    app.kubernetes.io/name: pat_client
spec:
  concurrencyPolicy: Forbid
  schedule: "0 0 * * *"
  startingDeadlineSeconds: 600
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: pat-client
              imagePullPolicy: IfNotPresent
              command:
                - ./pat_client
              volumeMounts:
                - name: secret
                  mountPath: "/app/secret"
          restartPolicy: OnFailure
