apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: not-used
spec:
  serviceName: "site1pool1bridge1"
  replicas: 2
  template:
    spec:
      containers:
        - env:
            - name: SERVERPOD
              value: "https://prod-useast-a.online.tableau.com/"
            - name: SITE
              value: "chandreshsandbox4"
            - name: USEREMAIL
              value: "chandresh.patel@tableau.com"
          image: 010465704656.dkr.ecr.us-west-2.amazonaws.com/tableau_bridge:near.23.0110.0804-2
          name: site1pool1bridge1
